receiver_email: "email@gmail.com" # email to send to
sender_email: "email@gmail.com" # email to send from 
password: "**** **** **** ****" # The app-password of the sender_email email
keyword: "Zürich" # Choose between Zürich and Winterthur
url_woko: "https://www.woko.ch/en/nachmieter-gesucht"  # Long-term listings
#url_woko: "https://www.woko.ch/en/untermieter-gesucht"  # Short-term listings (sublets)
#url_woko: "https://www.woko.ch/en/zimmer-in-zuerich"  # Both listings
timer: 120 # in s./ interval to update request
test_email: True
